version: '3.9'

services:
  web:
    build: .
    container_name: hms-web-1
    volumes:
      - .:/code
      - ./db.sqlite3:/code/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
